post http://localhost:3333/auth/signup
Content-Type: application/json

{
    "username":"abc",
    "password":"123456",
    "email":"ts5@deeeesttestt.com"
}

###
POST http://localhost:3333/auth/login
Content-Type: application/json

{
    "password":"123456",
    "email":"t5dest@testt.com"
}