post http://localhost:3333/auth/signup
Content-Type: application/json

{
    "username":"c",
    "password":"1256",
    "email":"tjfjfs5@deeeesttestt.com"
}

###
POST http://localhost:3333/auth/login
Content-Type: application/json

{
    "password":"123456",
    "email":"t5dest@testt.com"
}

###
POST http://localhost:3333/disks/add
Content-Type: application/json

{
  "name": "diskName",
  "description": "description",
  "location": "Somewhere",
  "imageURL": "https://someUrl.com",
  "userId": 292
}